"""PDF report generation service."""
from datetime import datetime

from fpdf import FPDF


class ReportService:
    """Service for generating PDF analysis reports."""

    def generate_report(self, prediction_data: dict) -> bytes:
        """Generate a PDF report for a prediction."""
        pdf = FPDF()
        pdf.add_page()
        pdf.set_auto_page_break(auto=True, margin=15)

        # Title
        pdf.set_font('Arial', 'B', 16)
        pdf.cell(0, 10, 'BrainTumorAI Analysis Report', ln=True, align='C')
        pdf.ln(10)

        # Horizontal line
        pdf.set_draw_color(0, 120, 200)
        pdf.set_line_width(0.5)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(10)

        # Analysis details
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Analysis Details', ln=True)
        pdf.ln(5)

        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 7, f"Analysis ID: {prediction_data.get('id', 'N/A')}", ln=True)
        pdf.cell(0, 7, f"Date: {prediction_data.get('created_at', datetime.utcnow().isoformat())}", ln=True)
        pdf.cell(0, 7, f"Original Filename: {prediction_data.get('original_filename', 'N/A')}", ln=True)
        pdf.ln(5)

        # Results
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Classification Results', ln=True)
        pdf.ln(5)

        pdf.set_font('Arial', '', 11)
        predicted_class = prediction_data.get('predicted_class', 'N/A')
        confidence = prediction_data.get('confidence', 0)
        pdf.cell(0, 7, f"Predicted Class: {predicted_class.capitalize()}", ln=True)
        pdf.cell(0, 7, f"Confidence: {confidence * 100:.2f}%", ln=True)
        pdf.ln(5)

        # Probabilities
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Class Probabilities', ln=True)
        pdf.ln(5)

        probabilities = prediction_data.get('probabilities', {})
        pdf.set_font('Arial', '', 11)
        for class_name, prob in probabilities.items():
            pdf.cell(0, 7, f"  {class_name.capitalize()}: {prob * 100:.2f}%", ln=True)
        pdf.ln(5)

        # Model info
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 8, 'Model Information', ln=True)
        pdf.ln(5)

        pdf.set_font('Arial', '', 11)
        pdf.cell(0, 7, f"Model Version: {prediction_data.get('model_version', 'N/A')}", ln=True)
        pdf.cell(0, 7, f"Processing Time: {prediction_data.get('processing_time_ms', 0):.2f} ms", ln=True)
        pdf.ln(10)

        # Disclaimer
        pdf.set_draw_color(0, 120, 200)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(5)

        pdf.set_font('Arial', 'I', 9)
        pdf.multi_cell(
            0, 5,
            'Disclaimer: This report is generated by an AI system and should not be '
            'used as a definitive medical diagnosis. Always consult with a qualified '
            'healthcare professional for medical decisions.'
        )

        return pdf.output()


report_service = ReportService()
